# Base image we are modifying from https://hub.docker.com/
FROM node:14.15.4-alpine3.10

# Set working directory
RUN mkdir -p /app/server
WORKDIR /app/server

# Install and cache app dependencies
COPY ./package.json /app/server
RUN npm install

COPY . /app/server

# Run final command to kick off server
CMD ["npm", "run", "server"]