# Base image we are modifying from https://hub.docker.com/
FROM node:14.15.4-alpine3.10

# Set working directory
RUN mkdir -p /app/
WORKDIR /app/

# Install and cache app dependencies
COPY ./package.json /app/
RUN npm install

COPY . /app/

# Run final command to kick off server
CMD ["npm", "run", "server"]